### ISSUE TITLE
Shutdown radare containers

### ISSUE THREAD

**Issue by maringuu** [fkie-cad/FACT_docker#32]
From #27 

> I noticed that after doing a `docker-compose stop` (or even `down`) that the radare containers stay up.
> 
> ```
> $ docker ps
> CONTAINER ID   IMAGE                           COMMAND                  CREATED      STATUS      PORTS                                               NAMES
> 22227f15e563   fkiecad/radare-web-gui:latest   "python3 src/serve.py"   2 days ago   Up 2 days                                                       radare_app_1
> 34e62c69975b   radare_server                   "/docker-entrypoint.…"   2 days ago   Up 2 days   80/tcp, 0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   radare_server_1
> ```
> 
> I am guessing that one of the intermediate containers start it but does not shut it down afterwards. Perhaps worth looking into.

Probably this has to be fixed in FACT_core

**Comment by jstucke** [comment]
The containers are stopped in `src/start_fact_frontend.py`:

```python
run_cmd_with_logging(f'docker-compose -f {COMPOSE_YAML} down')
```

The problem is probably that this line is only executed when the frontend is shut down "gracefully". If it is simply killed by docker it will not work. I don't see how this could be solved in FACT because if the process is just killed we can't handle it. I'm not sure how exactly `docker-compose down` is handled inside the containers, though (i.e. what kind of signal gets sent, etc.). So maybe there could be a way to fix this.

**Comment by frakman1** [comment]
If `docker-compose` is being used to launch FACT, then what is the correct method of shutting the frontend down gracefully?

**Comment by jstucke** [comment]
When running FACT outside of docker you would simply use Ctrl+C (so SIGINT) to stop FACT. That signal gets handled internally and a graceful shutdown is performed (including the shutdown of docker-compose for the radare web GUI). It seems when using docker-compose the shutdown is performed differently (could be SIGTERM, SIGKILL or something entirely different). I will have to investigate this and maybe make some adjustments to the signal handling in FACT.

**Comment by jstucke** [comment]
I tested it and it seems the signal submitted to the container when pressing Ctrl+C or executing `docker-compose stop` is `SIGTERM`. This means if we handle this signal in the FACT start scripts everything should work.
